services:
  - type: web
    name: fastapi-gpt-app
    env: python
    region: oregon  # or frankfurt, singapore, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value:   # Or set via Render dashboard
